In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from abdomen import AbdomenMRCT
from lungct import LungCT
import os

import matplotlib.pyplot as plt
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import numpy as np

In [2]:
# dataset = AbdomenMRCT("/mnt/rohit_data2/Abdomen-L2R/")
dataset = LungCT("/mnt/rohit_data2/LungCT_L2R", aug=True)

In [3]:
len(dataset)

34

In [4]:
ret = dataset[0]
# print(ret['source_img_path'], ret['target_img_path'])

[23.58508667  8.39488808 18.41658967]
torch.Size([4, 4])
tensor([[ 8.5982e-01, -3.2015e-01,  1.3796e-01, -1.8973e-02],
        [ 3.1600e-01,  8.7179e-01, -3.7405e-01,  4.2715e-02],
        [-4.9683e-04,  4.3216e-01,  8.5678e-01,  3.5483e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])


In [5]:
# ret['source_kps'].min(), ret['source_kps'].max()

In [7]:
# fixed_img = ret['source_img'].squeeze().numpy()
# moving_img = ret['target_img'].squeeze().numpy()
# fixed_label = ret['source_label'].squeeze().numpy()
# moving_label = ret['target_label'].squeeze().numpy()

# def plot_slices(slice_idx):
#     # Create a figure with 2 rows and 3 columns
#     fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    
#     # Plot fixed image and label
#     axes[0,0].imshow(fixed_img[slice_idx,:,:], cmap='gray')
#     axes[0,0].set_title('Fixed Image')
#     axes[0,0].axis('off')
    
#     axes[0,1].imshow(fixed_label[slice_idx,:,:], cmap='tab20')
#     axes[0,1].set_title('Fixed Label')
#     axes[0,1].axis('off')
    
#     # Overlay fixed image and label
#     axes[0,2].imshow(fixed_img[slice_idx,:,:], cmap='gray')
#     axes[0,2].imshow(fixed_label[slice_idx,:,:], alpha=0.3, cmap='tab20')
#     axes[0,2].set_title('Fixed Overlay')
#     axes[0,2].axis('off')
    
#     # Plot moving image and label
#     axes[1,0].imshow(moving_img[slice_idx,:,:], cmap='gray')
#     axes[1,0].set_title('Moving Image')
#     axes[1,0].axis('off')
    
#     axes[1,1].imshow(moving_label[slice_idx,:,:], cmap='tab20')
#     axes[1,1].set_title('Moving Label')
#     axes[1,1].axis('off')
    
#     # Overlay moving image and label
#     axes[1,2].imshow(moving_img[slice_idx,:,:], cmap='gray')
#     axes[1,2].imshow(moving_label[slice_idx,:,:], alpha=0.3, cmap='tab20')
#     axes[1,2].set_title('Moving Overlay')
#     axes[1,2].axis('off')
    
#     plt.tight_layout()
#     plt.show()

# # Create interactive slider
# interact(
#     plot_slices, 
#     slice_idx=widgets.IntSlider(
#         min=0,
#         max=fixed_img.shape[0]-1,
#         step=1,
#         value=fixed_img.shape[0]//2,
#         description='Slice:',
#         continuous_update=False
#     )
# )

In [8]:
fixed_img = ret['source_img'].squeeze().numpy()
moving_img = ret['target_img'].squeeze().numpy()

def plot_orthogonal_views(axial_idx, sagittal_idx, coronal_idx):
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    
    # Fixed image views
    axes[0,0].imshow(fixed_img[axial_idx,:,:], cmap='gray')
    axes[0,0].set_title('Fixed - Axial')
    axes[0,0].axis('off')
    
    axes[0,1].imshow(fixed_img[:,sagittal_idx,:], cmap='gray')
    axes[0,1].set_title('Fixed - Sagittal')
    axes[0,1].axis('off')
    
    axes[0,2].imshow(fixed_img[:,:,coronal_idx], cmap='gray')
    axes[0,2].set_title('Fixed - Coronal')
    axes[0,2].axis('off')
    
    # Moving image views
    axes[1,0].imshow(moving_img[axial_idx,:,:], cmap='gray')
    axes[1,0].set_title('Moving - Axial')
    axes[1,0].axis('off')
    
    axes[1,1].imshow(moving_img[:,sagittal_idx,:], cmap='gray')
    axes[1,1].set_title('Moving - Sagittal')
    axes[1,1].axis('off')
    
    axes[1,2].imshow(moving_img[:,:,coronal_idx], cmap='gray')
    axes[1,2].set_title('Moving - Coronal')
    axes[1,2].axis('off')
    
    plt.tight_layout()
    plt.show()

# Create interactive sliders
interact(
    plot_orthogonal_views,
    axial_idx=widgets.IntSlider(
        min=0,
        max=fixed_img.shape[0]-1,
        step=1,
        value=fixed_img.shape[0]//2,
        description='Axial:',
        continuous_update=False
    ),
    sagittal_idx=widgets.IntSlider(
        min=0,
        max=fixed_img.shape[1]-1,
        step=1,
        value=fixed_img.shape[1]//2,
        description='Sagittal:',
        continuous_update=False
    ),
    coronal_idx=widgets.IntSlider(
        min=0,
        max=fixed_img.shape[2]-1,
        step=1,
        value=fixed_img.shape[2]//2,
        description='Coronal:',
        continuous_update=False
    )
)

interactive(children=(IntSlider(value=96, continuous_update=False, description='Axial:', max=191), IntSlider(v…

<function __main__.plot_orthogonal_views(axial_idx, sagittal_idx, coronal_idx)>

In [43]:
ret = dataset[0]

[[ 0.89352253 -0.05015184  0.31856208]
 [-0.06134838  0.86251337  0.36312912]
 [-0.29370599 -0.33273272  0.89329131]] [ 0.0212963  -0.008266    0.01033552] [-22.12208373  18.28165943   3.27045885]
tensor([[ 0.8935, -0.0502,  0.3186,  0.0213],
        [-0.0613,  0.8625,  0.3631, -0.0083],
        [-0.2937, -0.3327,  0.8933,  0.0103],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])


In [44]:
fixed_img = ret['source_img'].squeeze().numpy()
moving_img = ret['target_img'].squeeze().numpy()

def torch2numpy(kps, X, Y, Z):
    kps[:, 0] = (kps[:, 0] + 1)*X/2 - 1/2
    kps[:, 1] = (kps[:, 1] + 1)*Y/2 - 1/2
    kps[:, 2] = (kps[:, 2] + 1)*Z/2 - 1/2
    return kps

Z, Y, X = fixed_img.shape

fixed_kps = torch2numpy(ret['source_kps'].squeeze().numpy() + 0, X, Y, Z)
moving_kps = torch2numpy(ret['target_kps'].squeeze().numpy() + 0, X, Y, Z)

print(fixed_kps.min(0), fixed_kps.max(0), X, Y, Z)


def plot_orthogonal_views(axial_idx, sagittal_idx, coronal_idx, s=4):
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    
    # Fixed image views
    axes[0,0].imshow(fixed_img[:,:,:].max(0), cmap='gray')
    axes[0,0].set_title('Fixed - Axial')
    axes[0,0].axis('off')

    axes[0,0].scatter(fixed_kps[:, 0], fixed_kps[:, 1], s=s)
    
    axes[0,1].imshow(fixed_img[:,:,:].max(1), cmap='gray')
    axes[0,1].set_title('Fixed - Sagittal')
    axes[0,1].axis('off')

    axes[0,1].scatter(fixed_kps[:, 0], fixed_kps[:, 2], s=s)
    
    axes[0,2].imshow(fixed_img[:,:,:].max(2), cmap='gray')
    axes[0,2].set_title('Fixed - Coronal')
    axes[0,2].axis('off')

    axes[0,2].scatter(fixed_kps[:, 1], fixed_kps[:, 2], s=s)
    
    # Moving image views
    axes[1,0].imshow(moving_img[axial_idx,:,:], cmap='gray')
    axes[1,0].set_title('Moving - Axial')
    axes[1,0].axis('off')
    axes[1,0].scatter(moving_kps[:, 0], moving_kps[:, 1], s=s)
    
    axes[1,1].imshow(moving_img[:,sagittal_idx,:], cmap='gray')
    axes[1,1].set_title('Moving - Sagittal')
    axes[1,1].axis('off')
    axes[1,1].scatter(moving_kps[:, 0], moving_kps[:, 2], s=s)

    
    axes[1,2].imshow(moving_img[:,:,coronal_idx], cmap='gray')
    axes[1,2].set_title('Moving - Coronal')
    axes[1,2].axis('off')
    axes[1,2].scatter(moving_kps[:, 1], moving_kps[:, 2], s=s)

    
    plt.tight_layout()
    plt.show()

# Create interactive sliders
interact(
    plot_orthogonal_views,
    axial_idx=widgets.IntSlider(
        min=0,
        max=fixed_img.shape[0]-1,
        step=1,
        value=fixed_img.shape[0]//2,
        description='Axial:',
        continuous_update=False
    ),
    sagittal_idx=widgets.IntSlider(
        min=0,
        max=fixed_img.shape[1]-1,
        step=1,
        value=fixed_img.shape[1]//2,
        description='Sagittal:',
        continuous_update=False
    ),
    coronal_idx=widgets.IntSlider(
        min=0,
        max=fixed_img.shape[2]-1,
        step=1,
        value=fixed_img.shape[2]//2,
        description='Coronal:',
        continuous_update=False
    )
)

[29.245426 36.108334 34.193493] [169.24445 176.8364  178.1609 ] 192 192 208


interactive(children=(IntSlider(value=104, continuous_update=False, description='Axial:', max=207), IntSlider(…

<function __main__.plot_orthogonal_views(axial_idx, sagittal_idx, coronal_idx, s=4)>

In [20]:
ret['source_kps'].squeeze().numpy()

array([[1.8690090e+09, 7.8144353e+09, 1.0529294e+10],
       [1.8690090e+09, 8.1541740e+09, 7.4876621e+09],
       [1.9539441e+09, 9.0035200e+09, 8.6575206e+09],
       ...,
       [1.3759861e+10, 8.5788472e+09, 7.4876621e+09],
       [1.3759861e+10, 1.0277540e+10, 7.4876621e+09],
       [1.4014665e+10, 6.7952195e+09, 7.7216338e+09]], dtype=float32)